version: '3.8'

services:
  anisette:
    image: dadoum/anisette-v3-server:latest
    container_name: anisette
    ports:
      - "6969:6969"
    volumes:
      - anisette_data:/home/AppInst/.config/anisette-v3
    restart: always
    networks:
      - mh-network

  macless-haystack:
    image: christld/macless-haystack:latest
    container_name: macless-haystack
    ports:
      - "6176:6176"
    volumes:
      - ./keys:/app/keys
    environment:
      - ANISETTE_SERVER=http://anisette:6969
    depends_on:
      - anisette
    stdin_open: true
    tty: true
    restart: always
    networks:
      - mh-network

volumes:
  anisette_data:

networks:
  mh-network:
    driver: bridge
